### ISSUE TITLE
hackatón

### ISSUE THREAD

**Issue by JJ** [josealozanop/H4A#3]
¿Vais a participar en el hackatón de proyectos? http://osl.ugr.es/category/concursos/certamen-ugr-de-proyectos-libres/

**Comment by bormolina** [comment]
Hola JJ, nos encantaría poder participar y habernos implicado más en el
transcurso del concurso, pero actualmente tanto yo como Jose trabajamos y
eso añadido al poryecto fin de carrera nos hace imposible participar en el
hackatón :(

Cuando termine el proyecto espero tener más tiempo libre y poder participar
activamente con vosotros echando una mano donde sea necesario. De todas
formas nuestro paso por el concurso no ha sido en vano, el proyecto está
liberado https://github.com/josealozanop/H4A y llevamos un desarrollo
activo del mismo.

Un saludo, Borja Molina Zea.

2015-03-05 19:52 GMT+01:00 Juan Julián Merelo Guervós <
notifications@github.com>:

> ¿Vais a participar en el hackatón de proyectos?
> http://osl.ugr.es/category/concursos/certamen-ugr-de-proyectos-libres/
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/josealozanop/H4A/issues/3.

## 

Borja Molina.

**Comment by JJ** [comment]
Bueno, si estáis trabajando estáis participando.

Un saludo
